### PR TITLE
Python version

### PR DESCRIPTION
**Pull request by lxhlxhlxh555**
Python plot should be improved

### CODE REVIEW

**Comment by IsmailM** [comment]
This is what I tried:

```
docker build -f Dockerfile-dev -t gc_dev .
docker run --rm -it -v $PWD:/GenomeChronicler gc_dev bash

# Then inside the shell:

# Try new python main script
python3 main.py --bamFile=/GenomeChronicler/NA12878wxs.bam --resultsDir /GenomeChronicler/out --GATKthreads 8

# Try old (perl) genomechronicler script 
genomechronicler --bamFile=/GenomeChronicler/NA12878wxs.bam --resultsDir /GenomeChronicler/out4 --GATKthreads 8
```

- [ ] The main.py version does not seem to work:
image

(suggests that the error is in `cleanBAMfile_noCHR(BAM_file)`)

- [ ] Add python dependencies to the dockerfile

```Dockerfile
RUN apt-get update && apt-get install -y python3-pip
RUN ln -s /usr/bin/python3 /usr/bin/python
RUN python -m pip install fire pandas tqdm matplotlib seaborn xlsxwriter
```

- [ ] After Installing Python dependencies, and re-running with the perl main script, I get the following error: 
image

**Comment by lxhlxhlxh555** [comment]
The vcf files I used for testing are attached. Both of them are temporarily generated during the NA12878wxs.bam processing. I saved them and used them just for testing in order to check if the pipeline can run through~ I don't know if they are as input right or not~
[NA12878wxs.g.vcf.zip](https://github.com/PGP-UK/GenomeChronicler/files/11157457/NA12878wxs.g.vcf.zip)
[NA12878wxs.genotypes.vcf.zip](https://github.com/PGP-UK/GenomeChronicler/files/11157458/NA12878wxs.genotypes.vcf.zip)

I tested the command "python3 main.py --bamFile=/GenomeChronicler/NA12878wxs.bam --resultsDir /GenomeChronicler/out --GATKthreads 8", and found a bug~ I didn't find it before, because I added some codes that it would skip processing the bam file when existing a cached cleaned bam file~ I have fixed it

**Comment by IsmailM** [comment]
- [ ] Update Dockerfile and Dockerfile-dev

```Dockerfile
RUN wget -qO- https://github.com/PGP-UK/GenomeChronicler/releases/download/0.91/reference.tar.gz | tar xvz

RUN wget -qO- https://github.com/PGP-UK/GenomeChronicler/releases/download/0.91/software.tar.gz | tar xvz software.linux && mv software.linux software

RUN apt update && apt-get install -y python3 python3-pip libssl-dev libcurl4-openssl-dev
RUN pip3 install fire pandas xlsxwriter tqdm matplotlib seaborn
```

- [ ] In the above specify specific versions of the python dependencies.
- [ ] At the moment, when running with the bam input, the tqdm gives an error (verbose not being an argument) and with tqdm, it doesn't seem to be doing anything.
image

- [ ] When removing tqdm, the output PDF has significantly less info:


image

**Comment by IsmailM** [comment]
Once the above has been fixed, we can replace the `cleanBAMfile_noCHR` command with the following:

```python
# print(f"\t +++ INFO: Reheadering the BAM file")
# cmd = f'''samtools reheader -c 'sed -E -e "s/(^@SQ.*\tSN:)chr/\1/g" -' {filename} > {filename}.clean.BAM'''
# subprocess.run(cmd, shell=True)
subprocess.run(f"samtools reheader -c 'perl -pe \"s/^(@SQ.*)(\tSN:)chr/\$1\$2/\"' {filename} > {filename}.clean.BAM", shell=True)

print(f"\t +++ INFO: Indexing the BAM file")
subprocess.run(f"samtools index -@ 6 {filename}.clean.BAM", shell=True)```

**Pull request merged**
